### ISSUE TITLE
Too-long filename on installation

### ISSUE THREAD

**Issue by UmanShahzad** [pipedrive/client-nodejs#319]
When I try to install this package with `yarn` I get this error because of a too-long filename:

```
error https://registry.yarnpkg.com/pipedrive/-/pipedrive-13.2.8.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENAMETOOLONG: name too long, open '/home/ubuntu/.cache/yarn/v6/npm-pipedrive-13.2.8-2409a3004fc399994f3083c253ff35971afe3432-integrity/node_modules/pipedrive/dist/model/AnyOfRecentsActivityRecentsActivityTypeRecentsDealRecentsFileRecentsFilterRecentsNoteRecentsPersonRecentsOrganizationRecentsPipelineRecentsProductRecentsStageRecentsUser.js'"
```

**Comment by SpaceOven** [comment]
It sure is a long name there. 🙂
Fixed in the latest release: https://github.com/pipedrive/client-nodejs/releases/tag/v15.0.0

**Comment by ramontayag** [comment]
Hmm still getting this:

```
yarn add pipedrive --latest
yarn add v1.22.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "async@3.2.4" is incompatible with requested version "async@^2.1.1"
warning Resolution field "ejs@3.1.7" is incompatible with requested version "ejs@^2.6.1"
warning Resolution field "urijs@1.19.11" is incompatible with requested version "urijs@1.18.10"
warning Resolution field "async@3.2.4" is incompatible with requested version "async@~1.0.0"
warning pipedrive > superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)
[3/5] Fetching packages...
error https://registry.yarnpkg.com/pipedrive/-/pipedrive-22.0.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENAMETOOLONG: name too long, open '/home/ramon/.cache/yarn/v6/npm-pipedrive-22.0.2-09285ee3b53d4674c6510e25c263477d22aecaf9-integrity/node_modules/pipedrive/dist/model/AnyOfRecentsActivityRecentsActivityTypeRecentsDealRecentsFileRecentsFilterRecentsNoteRecentsPersonRecentsOrganizationRecentsPipelineRecentsProductRecentsStageRecentsUser.js'"
```

I see that the file still exists in the repo as well, and so does the new one `AnyOfRecents`
